metatags:
  jsonld: false
  favicon: false
pages:
  body:
    images:
      formats: []
      responsive: false
      caption: true
      remote: true
      placeholder: none
    highlight: true
assets:
  images:
    optimize: false
static:
  exclude:
    - '*.phar*'
layouts:
  images:
    formats: []
    responsive: false
serviceworker:
  enabled: false
optimize:
  enabled: false
